modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="morb"
version="0.1.0"
displayName="Morb"
credits="Created in MCreator. "
displayURL="https://github.com/GURU909/Morb"
authors="GURU909"
description='''
It's Morbin Time
'''

[[dependencies.morb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




